---
sudo: false
language: node_js
node_js:
  - '10'
install:
  - node -v
before_script:
  - yarn
cache:
  directories:
    - node_modules
  yarn: true

git:
  depth: 3

script:
  - yarn lint
  - yarn test
  - yarn build:lib
  - yarn build:styleguide

after_success:
  - yarn coveralls
