---
sudo: false
language: node_js
node_js:
  - '10'
install:
  - node -v
before_script:
  - yarn
cache:
  directories:
    - node_modules
  yarn: true

git:
  depth: 3

env:
  global:
    - BUNDLESIZE_GITHUB_TOKEN=3bdab43e295826ad67570bdb963f87c8ebc24e54

script:
  - yarn lint
  - yarn test
  - yarn build:lib
  - yarn build:styleguide
  - yarn checksize

after_success:
  - yarn coveralls
