#!/bin/bash

componentFile=$1
componentName="$(tr '[:lower:]' '[:upper:]' <<< ${componentFile:0:1})${componentFile:1}"

cd ../src/lib/components
mkdir $componentFile
touch $componentFile/$componentFile.js
touch $componentFile/$componentFile.stories.js
touch $componentFile/$componentFile.test.js
touch $componentFile/$componentFile.module.scss
touch $componentFile/index.js
echo "import $componentName from './$componentFile';\n\nexport default $componentName;" > "$componentFile/index.js"
echo "import React from 'react';\nimport renderer from 'react-test-renderer';\nimport $componentName from './$componentFile.js';\n\ndescribe('$componentName', () => {\n\tit('renders properly', () => {\n\t\tconst tree = renderer\n\t\t\t.create(\n\t\t\t\t<$componentName />,\n\t\t\t)\n\t\t\t.toJSON();\n\t\texpect(tree).toMatchSnapshot();\n\t});\n});" > "$componentFile/$componentFile.test.js"
echo "import React from 'react';\nimport { select } from '@storybook/addon-knobs';\nimport WarningBlock from './$componentFile';\nimport themeOptions from '../../styles/themeOptions';\n\nexport default {\n\ttitle: '$componentName',\n\tparameters: {\n\t\tjest: ['$componentFile.test.js'],\n\t},\n};\n\nexport const defaultComponent = () => (\n\t<$componentName theme={select('theme', themeOptions, 'plain')}>\n\t\tChildrenContent_TO_BE_REPLACED\n\t</$componentName>\n);"
echo "export { default as $componentName } from './$componentFile';" >> "index.js"
echo "@import '../../styles/variables/variables.module.scss';\n@import '../../styles/themes/themes.module.scss';" > "$componentFile/$componentFile.module.scss"
echo "import React, { PureComponent } from 'react';\nimport PropTypes from 'prop-types';\nimport { componentPropTypes, defaultComponentPropTypes } from '../../utils/componentPropTypes';\nimport styles from './$componentFile.module.scss';\n\nexport default class $componentName extends PureComponent {\n\tstatic propTypes = {\n\t\t...componentPropTypes,\n\t};\n\n\tstatic defaultProps = {\n\t\t...defaultComponentPropTypes,\n\t};\n\n\trender() {\n\t\tconst { theme } = this.props;\n\t\treturn (\n\t\t\t<div className={styles[\`theme-\${theme}\`]}></div>\n\t\t);\n\t}\n}\n" >> "$componentFile/$componentFile.js"
