#!/bin/bash

VERSION=$1

cd ..
npm version $VERSION
git tag v$VERSION -m "Publish new version of blueprint library $VERSION"
git add package.json
git commit -m "Publish new version of blueprint library $VERSION"
git push origin master && git push --tags origin master
git subtree push --prefix docs origin gh-pages
npm publish
