name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "kba@aimementoring.com"
      - run: git config --global user.name "Automatic Deploy"
      - run: npm install
      - run: export GITHUB_TOKEN="81c54f0f97dda0c4e9d8343697e07eb08dbf81f7"
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN:  81c54f0f97dda0c4e9d8343697e07eb08dbf81f7
